### ISSUE TITLE
bug: set_syslog_server.yml

### ISSUE THREAD

**Issue by mcgonagle** [mcgonagle/ansible_f5#11]
fatal: [54.226.107.199 -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/var/folders/_r/ht1v5f8n31s9cm78mjn9scpw0000gn/T/ansible_D3j9VJ/ansible_module_bigip_remote_syslog.py\", line 224, in <module>\n    main()\n  File \"/var/folders/_r/ht1v5f8n31s9cm78mjn9scpw0000gn/T/ansible_D3j9VJ/ansible_module_bigip_remote_syslog.py\", line 218, in main\n    results = mm.exec_module()\n  File \"/var/folders/_r/ht1v5f8n31s9cm78mjn9scpw0000gn/T/ansible_D3j9VJ/ansible_module_bigip_remote_syslog.py\", line 148, in exec_module\n    changes = self.changes.to_return()\nAttributeError: 'NoneType' object has no attribute 'to_return'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

**Comment by mcgonagle** [comment]
"msg": "400 Unexpected Error: Bad Request for uri: https://54.226.107.199:443/mgmt/tm/sys/snmp/\nText: u'{\"code\":400,\"message\":\"one or more properties must be specified\",\"errorStack\":[],\"apiError\":26214401}'"
}

**Comment by caphrim007** [comment]
@mcgonagle the remote_syslog module should now be complete
